cd $PBS_O_WORKDIR

source ~cmssoft/shrc
eval `scramv1 runtime -sh`
export X509_USER_PROXY=~/.x509_user_proxy

root -b -q -l '../../FillHistoW.C("/home/kencall/development/RecHitSpectra/CMSSW_7_4_3/src/METPlots/RecHitSpectra/test/DATA/SingleNeutrino25ns/HcalRecHitSpectra-SingleNeutrino25ns-af-fixed.root","Histos-SingleNeutrino25ns-WeightedTo-ZeroBias254906-af.root","single","nVertexWeights-SingleNeutrino25-WeightedTo-ZeroBias254906.root")'
